--TRIGGER--
CREATE OR REPLACE TRIGGER GEN_PROD_BATCH_TRG 
BEFORE INSERT
ON GEN_PROD_BATCH
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := NEXT_ID('GEN_PROD_BATCH');
END;
/

--*****************
CREATE OR REPLACE TRIGGER HRM_INCREMENT_XL_TRG 
BEFORE INSERT
ON HRM_INCREMENT_XL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  :new.ID := NEXT_ID('HRM_INCREMENT_XL');
END;
/

--******************

CREATE OR REPLACE TRIGGER UNIT_DEPT_TBL_TRG 
BEFORE INSERT
ON UNIT_DEPT_TBL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column UNIT_DEPT_NO
  :new.UNIT_DEPT_NO := NEXT_GEN_ID('UNIT_DEPT_TBL','UNIT_DEPT_NO');
END UNIT_DEPT_TBL_TRG;
/